language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
addons:
  apt:
    packages:
      - sshpass
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git
  - sudo apt-get install -y libboost-all-dev 
  - sudo apt-get install -y libpqxx-3.1 libpqxx3-dev 
  - sudo apt-get install -y libconfig++ 
  - sudo apt-get install -y cmake 
  - sudo apt-get install -y libtinyxml2-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y root-system
script:
    - mkdir -p DBHandler/Config
    - export SSHPASS=$SPHINX_PASSWORD
    - sshpass -e scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SPHINX_USERNAME@sphinx.if.uj.edu.pl:/home/framework_configs/configDB.cfg DBHandler/Config/
    - ls DBHandler/Config/
    - sshpass -e scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SPHINX_USERNAME@sphinx.if.uj.edu.pl:/home/framework_configs/configDB.cfg.koza DBHandler/Config/
    - sshpass -e scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SPHINX_USERNAME@sphinx.if.uj.edu.pl:/home/framework_configs/ReadMe.txt DBHandler/Config/
    - mkdir build
    - cd build
    - cmake ..
    - cp ../DBHandler/Config/configDB.cfg.koza ../DBHandler/Config/configDB.cfg;
    - make all tests
    - cd tests
    - ./run_tests.pl -f xml
    - chmod a+x parseXML.py
    - ./parseXML.py
