name: j-pet-continuous-integration-tests
on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
   
    steps:
    - uses: actions/checkout@v2
    - name: system update
      run: |
       sudo apt-get -qq update
       sudo apt-get install -y git libboost-all-dev libtbb-dev cmake
      
    - name: download  ROOT 
      run: |
        wget https://root.cern/download/root_v6.12.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
        tar xzf root_v6.12.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
    - name: cmake,  make and run tests
      run: |
        source root/bin/thisroot.sh
        mkdir build
        cd build
        cmake ..
        make all tests -j4
        source bin/thisframework.sh
        ctest -j6 -C Debug -T test --output-on-failure


